### ISSUE TITLE
Clean up `Modding` and related articles

### ISSUE THREAD

**Issue by MChecaH** [ppy/osu-wiki#11995]
This issue is being tracked and developed in [the following `#osu-wiki` thread](https://discord.com/channels/188630481301012481/1273333496240410704/1273336723681575062).

**Summary:** Resources on "How to mod" are split between multiple articles, and it is not intuitive for newer users to find this information, obfuscating what should otherwise be basic knowledge. The point of the rework is to reduce the number of articles referencing ways and explanations on "How to mod", clean up the affected articles, and finally making it more intuitive for both new and experienced users what Modding entails in the osu! ecosystem.

This issue will be split in multiple, sequential tasks and subsequent PRs.
```[tasklist]
### Tasks
- [ ] Clean up [Code of conduct for modding and mapping](https://osu.ppy.sh/wiki/en/Rules/Code_of_conduct_for_modding_and_mapping).
- [ ] Clean up the [Modding](https://osu.ppy.sh/wiki/en/Modding) portal page.
- [ ] Create new article `Modding guide` (Under `/wiki/Guides/`).
- [ ] Create new article `Modding expectations` (Under `/wiki/Modding/`).
- [ ] Miscel·laneous work on other articles. The list of all currently listed articles can be tracked [here](https://docs.google.com/document/d/13dqaH20XPzQQiNzm3IyzG2WlYEyUoIY_kag9qBFqR9Y/edit?usp=sharing).
```
