### ISSUE TITLE
German Wiki Completion

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu-wiki#1373]
## Article Listing

- [x] About (en: 5, de: 5) [#1391]
- [ ] Accuracy (en: 76)
- [ ] Article Styling Criteria (en: 585)
    - [ ] Images (en: 93)
    - [ ] News (en: 139)
- [x] BanchoBot (en: 164, de: 24, **outdated**) [#1377]
- [ ] BBCode (en: 391)
- [x] Beatmapping (en: 56, de: 41) [#1415]
- [ ] Beatmaps (en: 74)
    - [ ] Packs (en: 42)
- [ ] Beatmap Discussion (en: 221)
- [x] Beatmap Editor (en: 22, de: 20)
    - [x] AiMod (en: 176, de: 175)
    - [x] Beat Snap Divisor (en: 124, de: 124)
    - [ ] Compose (en: 356)
    - [ ] Design (en: 176)
    - [x] Distance Snap (en: 43, de: 8)
    - [x] Kiai Time (en: 23, de: 24)
    - [x] Menu (en: 256, de: 254)
    - [ ] SB Load (en: 62)
    - [ ] Song Setup (en: 257)
    - [ ] Timelines (en: 135)
    - [ ] Timing (en: 19)
- [ ] Best Of (en: 322)
    - [ ] 2009 (en: 44)
    - [ ] 2010 (en: 63)
    - [ ] 2011 (en: 115)
    - [ ] 2012 (en: 110)
    - [ ] 2013 (en: 1390)
    - [ ] 2014 (en: 1444)
    - [ ] 2015 (en: 2102)
    - [ ] 2016 (en: 1865)
- [x] Chat Console (en: 106, de: 113)
- [ ] Contests (en: 245)
- [ ] Difficulties (en: 60)
    - [x] Easy (en: 80, de: 38)
    - [ ] Expert (en: 26)
    - [ ] Futsuu (en: 40)
    - [x] Hard (en: 41, de: 11)
    - [x] Insane (en: 16, de: 21)
    - [ ] Kantan (en: 32)
    - [ ] Muzukashii (en: 47)
    - [x] Normal (en: 56, de: 27)
    - [ ] Oni (en: 28)
    - [ ] Ura Oni (en: 27)
- [x] Disambiguation (en: 10, de: 10) [#1410] 
    - [x] Bancho (en: 6, de: 6) [#1410]
    - [x] Easy (en: 11, de: 11) [#1410]
    - [x] EZ (en: 11, de: 11) [#1410]
    - [x] Mod (en: 7, de: 7) [#1410]
- [x] Do you really want to ask peppy (en: 15, de: 15)
- [ ] FAQ (en: 731)
- [ ] Game Modes (en: 8)
    - [ ] osu! (en: 379)
    - [ ] osu!catch (en: 281)
    - [ ] osu!mania (en: 435)
    - [ ] osu!taiko (en: 335)
- [ ] Game Modifiers (en: 740)
    - [ ] Summary (en: 77)
- [ ] Glossary (en: 929)
- [ ] Guides (en: 53)
    - [x] Adding Custom Hit Sounds (en: 45, de: 50)
    - [ ] Audio Editing (en: 150)
    - [x] Beginner's Tutorial (en: 156, de: 150)
    - [ ] BSS Issues (en: 44)
    - [ ] Changing the Artist or Title (en: 35)
    - [ ] Changing the Title Text (en: 87)
    - [ ] Collab Information (en: 61)
    - [ ] Compressing Files (en: 132)
    - [ ] Cropping with Complex Backgrounds (en: 46)
    - [ ] Cropping with Simple Backgrounds (en: 43)
    - [ ] Custom Hit Sound Library (en: 111)
    - [x] Custom Sample Overrides (en: 64, de: 48)
    - [ ] Discord RPC (en: 42)
    - [ ] Getting Songs From Video Games (en: 57)
    - [x] Getting Your Map Modded (en: 40, de: 38)
    - [x] GL Support Issues (en: 34, de: 34)
    - [x] How To Get Your Map Ranked (en: 28, de: 27)
    - [ ] How to Play osu!mania (en: 0)
    - [ ] How to Run osu! on Your Mac Without Using Boot Camp (en: 207)
    - [ ] How to Time Songs (en: 189)
    - [ ] How to Use the Offset Wizard (en: 23)
    - [ ] Live Streaming osu! (en: 317)
    - [ ] Making Properly Centered Spinners (en: 104)
    - [ ] Music Theory (en: 93)
    - [x] osu!mania Mapping Guide (en: 339, de: 425)
    - [ ] Recording osu! (en: 74)
    - [ ] Searching and Downloading Beatmaps (en: 0)
    - [ ] Setting the Offset on the Correct Beat (en: 30)
    - [ ] Starting a Beatmap Project (en: 38)
    - [ ] Tablet Purchase (en: 78)
    - [ ] Tips and Tricks on Skill Improvement (en: 0)
    - [ ] Videos From Youtube (en: 24)
- [ ] Help Centre (en: 1000)
- [ ] History of osu! (en: 22)
    - [ ] 2007 (en: 99)
    - [ ] 2008 (en: 79)
    - [ ] 2009 (en: 35)
    - [ ] 2010 (en: 3)
    - [ ] 2011 (en: 11)
    - [ ] 2012 (en: 108)
    - [ ] 2013 (en: 140)
    - [ ] 2014 (en: 27)
    - [ ] 2015 (en: 41)
    - [ ] 2016 (en: 129)
    - [ ] 2017 (en: 134)
    - [ ] 2018 (en: 132)
    - [ ] osu! wiki (en: 32)
- [x] Hit Objects (en: 69, de: 37)
- [ ] How You Can Help! (en: 80)
- [x] Installation (en: 66, de: 66) [#1369]
- [x] Interface (en: 298, de: 183)
- [x] Internet Relay Chat (en: 81, de: 72)
- [ ] Legal (en: 0)
    - [ ] Copyright (en: 67)
    - [ ] Privacy (en: 119)
    - [ ] Terms (en: 108)
- [ ] Main Page (en: 0)
- [ ] Mapping Techniques (en: 150)
    - [ ] Basics (en: 103)
    - [ ] Formations (en: 166)
    - [ ] Jumps (en: 63)
    - [ ] Making Good Sliders (en: 197)
    - [ ] Rhythm (en: 195)
    - [ ] Sliders (en: 180)
    - [ ] Spinners (en: 48)
    - [ ] Unrankable (en: 46)
- [x] Mascots (en: 99, de: 235, **outdated**)
    - [ ] Gallery (en: 113)
- [x] Medals (en: 127, de: 110)
    - [ ] Beatmap Packs 0916 (en: 422)
- [ ] Modding (en: 258)
- [ ] Multi (en: 494)
- [ ] Official Songs (en: 66)
- [x] Options (en: 423, de: 791, **outdated**)
    - [ ] Keyboard Bindings (en: 155)
    - [ ] Offset Wizard (en: 36)
- [x] osu!academy (en: 57, de: 55)
- [x] osu!api (en: 11, de: 11)
- [ ] osu!stream (en: 466)
    - [ ] Song List (en: 267)
- [x] osu!supporter (en: 56, de: 67, **outdated**)
- [x] osu!talk (en: 93, de: 45)
- [ ] osu!tourney (en: 15)
    - [ ] Multiplayer Usage (en: 39)
    - [ ] Prizes (en: 93)
    - [ ] Setup (en: 39)
    - [ ] Skinning (en: 23)
    - [ ] Spectator Usage (en: 44)
    - [ ] Tournament Management Commands (en: 67)
    - [ ] Troubleshooting (en: 56)
- [x] osu! File Formats (en: 92, de: 38)
    - [ ] Db (file format) (en: 183)
    - [x] Osb (file format) (en: 4, de: 4)
    - [x] Osk (file format) (en: 4, de: 10)
    - [ ] Osr (file format) (en: 94)
    - [ ] Osu (file format) (en: 506)
    - [x] Osz (file format) (en: 4, de: 10)
- [ ] osu! Program Files (en: 131)
    - [ ] User Configuration File (en: 230)
- [ ] osu! wiki Contribution Guide (en: 108)
    - [ ] Common Issues (en: 80)
    - [ ] GitHub Desktop (en: 105)
    - [ ] GitHub Web Interface (en: 105)
- [ ] People (en: 12)
    - [ ] Beatmap Nominators (en: 175)
        - [ ] Beatmap Veto (en: 58)
        - [ ] Divisions (en: 135)
        - [ ] General Information (en: 55)
        - [ ] Rules (en: 66)
    - [x] Community Contributors (en: 110, de: 33, **outdated**)
    - [x] Global Moderation Team (en: 95, de: 98, **outdated**)
    - [x] Language Moderators (en: 66, de: 66)
    - [x] osu! Alumni (en: 254, de: 253)
    - [x] Quality Assurance Team (en: 40, de: 36, **outdated**)
        - [ ] Blog (en: 67)
    - [ ] Staff Log (en: 1166)
    - [x] Support Team (en: 39, de: 39)
    - [x] The Team (en: 89, de: 61, **outdated**)
- [ ] Performance Points (en: 171)
- [ ] Play Styles (en: 169)
- [ ] Projects (en: 211)
- [ ] Ranking Criteria (en: 286)
    - [ ] Code of Conduct (en: 69)
    - [ ] Difficulty Naming (en: 116)
    - [ ] osu! (en: 205)
        - [ ] Scaling BPM (en: 26)
    - [ ] osu!catch (en: 178)
    - [x] osu!mania (en: 85, de: 92)
    - [x] osu!taiko (en: 163, de: 63)
    - [ ] Skin Set List (en: 345)
    - [ ] Song Content Rules (en: 38)
    - [ ] Timing Songs With 8-Signatures (en: 46)
- [x] Registration (en: 22, de: 22) [#1370]
- [ ] Replay (en: 310)
- [ ] Reporting Bad Behaviour (en: 100)
    - [ ] Handling Foul Play (en: 80)
- [x] Rules (en: 80, de: 74)
- [ ] Score (en: 328)
    - [ ] ScoreV1 (en: 178)
- [x] Shortcut Key Reference (en: 287, de: 176, **outdated**)
- [ ] Sitemap (en: 278)
- [ ] Skinning (en: 32)
    - [x] Compendium (en: 373, de: 373) [#1389]
    - [ ] FAQ (en: 300)
    - [ ] Guides and Important Threads (en: 30)
    - [ ] History (en: 258)
    - [ ] Interface (en: 2489)
    - [ ] osu! (en: 767)
    - [ ] osu!catch (en: 299)
    - [ ] osu!mania (en: 563)
    - [ ] osu!taiko (en: 528)
    - [ ] Sounds (en: 1266)
- [ ] Skinning Tutorial (en: 41)
    - [ ] Interface (en: 647)
    - [ ] osu! (en: 77)
    - [ ] osu!catch (en: 105)
    - [ ] osu!mania (en: 106)
    - [ ] osu!taiko (en: 131)
    - [ ] Sounds (en: 37)
- [ ] Storyboarding (en: 12)
- [x] Storyboards (en: 48, de: 53)
    - [x] Maps (en: 153, de: 127)
- [x] Storyboard Scripting (en: 20, de: 20)
    - [x] Audio (en: 34, de: 34)
    - [ ] Cheat Sheet (en: 246)
    - [ ] Commands (en: 275)
    - [ ] Compound Commands (en: 93)
    - [x] General Rules (en: 108, de: 107)
    - [x] Objects (en: 74, de: 75)
    - [x] osu! File Toggles (en: 13, de: 13)
    - [ ] Shorthand (en: 78)
    - [ ] Variables (en: 47)
- [ ] Submission (en: 145)
    - [x] Beatmap Ranking Procedure (en: 44, de: 37)
- [x] Tournaments (en: 191, de: 75, **outdated**)
    - [ ] ANZT (en: 0)
        - [ ] 2018 Summer (en: 333)
    - [ ] ATS (en: 0)
        - [ ] 2018 (en: 518)
    - [ ] CFC (en: 0)
        - [ ] 2018 (en: 235)
    - [ ] CJB (en: 0)
        - [ ] 2018 (en: 0)
            - [ ] 4K (en: 315)
    - [ ] CMT 4K (en: 0)
        - [ ] 2017 (en: 437)
    - [x] Countries that participated in osu! tournaments (en: 358, de: 351)
    - [ ] CWC (en: 0)
        - [ ] 2014 (en: 542)
        - [ ] 2015 (en: 582)
        - [ ] 2016 (en: 601)
        - [ ] 2017 (en: 535)
        - [ ] 2018 (en: 543)
    - [ ] DMX (en: 0)
        - [ ] 2 (en: 491)
    - [ ] IGTS (en: 0)
        - [ ] 2018 (en: 411)
    - [ ] LMS (en: 0)
        - [ ] Shift (en: 0)
            - [ ] 1 (en: 541)
    - [ ] MWC (en: 0)
        - [ ] 2014 (en: 615)
        - [ ] 2015 (en: 496)
        - [ ] 2016 (en: 0)
            - [ ] 4K (en: 519)
            - [ ] 7K (en: 479)
        - [ ] 2017 (en: 0)
            - [ ] 4K (en: 495)
            - [ ] 7K (en: 391)
        - [ ] 2018 (en: 0)
            - [ ] 4K (en: 378)
            - [ ] 7K (en: 449)
    - [ ] osu! Tag Team Multiplayer Tournament (en: 244)
    - [ ] OWC (en: 0)
        - [ ] 1 (en: 238)
        - [ ] 2 (en: 333)
        - [x] 2013 (en: 518, de: 562, **outdated**)
        - [x] 2014 (en: 519, de: 586, **outdated**)
        - [x] 2015 (en: 550, de: 313)
        - [ ] 2016 (en: 536)
        - [ ] 2017 (en: 527)
        - [ ] 3 (en: 370)
    - [ ] OZT (en: 0)
        - [ ] 2018 (en: 120)
    - [ ] RMoT Invitational (en: 0)
        - [ ] 2 (en: 118)
        - [ ] 5 (en: 186)
    - [ ] SOFT (en: 0)
        - [ ] 3 (en: 799)
    - [ ] SS Tournament (en: 0)
        - [ ] 2018 (en: 381)
    - [ ] Template (en: 150)
    - [ ] THOM CUP (en: 0)
        - [ ] 1 (en: 625)
    - [ ] TSC (en: 0)
        - [ ] 1 (en: 294)
    - [ ] TWC (en: 0)
        - [ ] 2011 (en: 426)
        - [ ] 2014 (en: 414)
        - [x] 2015 (en: 579, de: 183)
        - [ ] 2016 (en: 510)
        - [ ] 2017 (en: 508)
        - [ ] 2018 (en: 500)
- [ ] Tournament Drawings (en: 91)
- [ ] Twitter (en: 13)
- [ ] Visual Settings (en: 19)
- [ ] Welcome (en: 47)
