### ISSUE TITLE
Misc. formatting issues

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2275]
adding onto #2031

- [ ] Strip BOM (#2274)
- [x] HitObject -> Hit object (changing caps where necessary) (#2064)
- [ ] Remove whitespace from tables
- [ ] Standardize image filenames (only hyphens for separating words) + ASC
- [x] Remove code styling from headers (#2062)
- [ ] Match article titles to their folder names (except cases where it makes sense to have different)
- [ ] Link users/beatmaps/etc by ID instead of name
- [x] Put osu.ppy.sh in front of osu! links (#2076)
- [ ] Remove tabs
- [x] Remove trailing (single) spaces (#2067)
- [x] Remove other kinds of whitespace not in ASCII (#2063)
- [ ] Add pipes to tables without pipes on the ends
- [ ] Fix old MediaWiki image entries
- [ ] Limit word boundary whitespace to a single space in normal paragraphs
- [ ] Make all headers use hashes instead of underscoring lines
- [ ] Don't use horizontal rules before headers
- [ ] Remove slashes from anchors
- [ ] Remove trailing slashes from links
- [ ] Remove useless newlines
- [ ] Handle news.ppy.sh links
- [ ] Handle w.ppy.sh images
- [ ] Convert /beatmaps/ links into /beatmapsets/
- [ ] Other MediaWiki things (expand this later)
- [ ] Handle special variables (?m=0, etc) on /beatmap(set)s and /users
- [ ] Point /p/ links to new site
- [ ] Point /forum/<module> links to new site

**Comment by MegaApplePi** [comment]
> Single-space lists

So, we going with single spaces for lists? 

~~nts I wrote a thing explaining why I thought we should use 4 characters. Only to cut myself off, realising that it is some kind of hypothetical that would only occur if we are in need of long and heavily indented lists. /shrug~~

**Comment by cl8n** [comment]
oh that is sort of misleading how I wrote it sorry. i dont mean the indenting, I mean the amount of blank lines between bullets in a list (nearly all lists should have no blank lines, but some do for seemingly no reason)

**Comment by TicClick** [comment]
@cl8n this is something you have the most context for -- wanna tick some boxes/add short explanations for what needs to be done, so that others could pick some tasks up?

**Comment by cl8n** [comment]
i don't think there is more explanation to add to these, they are all as straightforward as written, just annoying or very time consuming to apply across the whole wiki and verify that it was done correctly. iirc this was related to a remark extension i was working on at the time as well

the list is probably pretty outdated at this point. issue was last edited july 2020 and I haven't been keeping up

**Comment by TicClick** [comment]
to put it another way, I don't understand the following items:

- Put osu.ppy.sh in front of osu! links
- Fix old MediaWiki image entries
- Handle news.ppy.sh links
- Handle w.ppy.sh images
- Other MediaWiki things (expand this later)
- enforce sitemap being changed

**Comment by TPGPL** [comment]
- **Put osu.ppy.sh in front of osu! links** - for some time we were stripping the `osu.ppy.sh` URL from all links pointing to the osu! site; at last that was reverted and there are no more occurrences of that iirc?
-  **enforce sitemap being changed** is from a time when the sitemap was maintained manually so this one is done too
- **Handle news.ppy.sh links** - alternative links pointing to news posts, fixed too
- **Handle w.ppy.sh images** - a leftover from MediaWiki - some images were displayed through links, not files in the repo; fixed too
- **Fix old MediaWiki image entries** - some images had weird MediaWiki leftovers like `fig:` in tooltips, should be fixed too?
