### ISSUE TITLE
Add Article Stubs (Beatmaps)

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-wiki#3151]
See the main issue https://github.com/ppy/osu-wiki/issues/3143
See the project: https://github.com/ppy/osu-wiki/projects/3

Here you find all article stubs that need to be created. Some articles might already exist. Some articles can be deemed unnecessary as singular article and be summed up into a bigger article. 

Many of these singular topics are included as subset in some articles already or information is scattered around multiple articles. These articles might need to be split up into multiple ones and information must be pulled together into one common article then (e.g. https://github.com/ppy/osu-wiki/tree/master/wiki/Glossary)

Each article should only contain information of one topic. 

You can claim articles beforehand. Just comment here.

- [x] Beatmap
- [x] ~~Beatmap Download - Has a [guide in Chinese](https://osu.ppy.sh/wiki/zh/Guides/Searching_and_Downloading_Beatmaps) that needs to be translated/adapted to English~~ https://github.com/ppy/osu-wiki/issues/8128
---
- [x] **Beatmap submission**
- [x] Beatmap Set #3405
- [x] Beatmap Spread https://github.com/ppy/osu-wiki/pull/9036
---
- [x] .osu file
---
- [x] **Difficulty**
- [x] Difficulty name
---
- [x] **Beatmap creator**
- [x] Guest difficulty
- [x] Guest mapper (covered in *guest difficulty*)
- [x] Collaborative difficulty #3404
---
- [x] **Beatmap creation** https://osu.ppy.sh/wiki/en/Beatmapping
- [x] Stack leniency https://github.com/ppy/osu-wiki/pull/9028
- [x] Beat Snap https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Beat_Snap
- [x] Grid Snap https://osu.ppy.sh/wiki/en/Grid_snapping
- [x] Time-distance equality #3488
- [x] Distance Snap https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Distance_snap
- [x] Overlap #3144
- [x] Editor [Client/Beatmap_editor](https://osu.ppy.sh/wiki/en/Client/Beatmap_editor) | [Client/Beatmap_editor/Menu](https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Menu) | [Client/Beatmap_editor/Timelines](https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timelines) | [Help_centre/Beatmapping](https://osu.ppy.sh/wiki/en/Help_centre/Beatmapping)
---
- [x] **Music Theory** #3577
- [x] Beat #3577
- [x] Layer https://github.com/ppy/osu-wiki/pull/9023
- [x] Syncopation https://github.com/ppy/osu-wiki/pull/6995
- [x] Rhythm https://github.com/ppy/osu-wiki/pull/6995
- [x] Downbeat https://osu.ppy.sh/wiki/en/Downbeat
- [x] Measure https://github.com/ppy/osu-wiki/pull/6995
- [x] Tempo https://github.com/ppy/osu-wiki/pull/6995
---
- [x] **Pattern** https://osu.ppy.sh/wiki/en/Beatmap/Pattern
- [x] Jump https://osu.ppy.sh/wiki/en/Beatmap/Pattern/Jump
- [x] Stream https://osu.ppy.sh/wiki/en/Beatmap/Pattern/Stream
- [x] Stack https://github.com/ppy/osu-wiki/pull/3145
- [x] Flow https://github.com/ppy/osu-wiki/pull/7407
- [x] Antiflow https://osu.ppy.sh/wiki/en/Beatmapping/Antiflow
- [x] Walk https://osu.ppy.sh/wiki/en/Gameplay/Walk
- [x] Anchor https://github.com/ppy/osu-wiki/pull/8595
- [x] Bracket https://github.com/ppy/osu-wiki/pull/8595
- [x] Chord https://github.com/ppy/osu-wiki/pull/8595
- [x] Chordstream https://github.com/ppy/osu-wiki/pull/8595
- [x] Grace https://github.com/ppy/osu-wiki/pull/8595
- [x] Hand https://github.com/ppy/osu-wiki/pull/8595
- [x] Trill https://github.com/ppy/osu-wiki/pull/8595
- [x] Jumptrill https://github.com/ppy/osu-wiki/pull/8595
- [x] Jack https://github.com/ppy/osu-wiki/pull/8595
- [x] Minijack https://github.com/ppy/osu-wiki/pull/8595
- [x] Roll https://github.com/ppy/osu-wiki/pull/8595
- [x] Shield https://github.com/ppy/osu-wiki/pull/8595
- [x] Split-jumptrill https://github.com/ppy/osu-wiki/pull/8595
---
- [x] Combo Colour #3192
- [x] Kiai time
- [x] Countdown #3194
- [x] Break Time #3488
- [x] Epilepsy Warning https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Song_Setup#design
- [x] Applause https://osu.ppy.sh/wiki/en/Skinning/Sounds#game-screens
---
- [x] **Timing** [Beatmap_editor/Timing](https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timing) | [Beatmapping/Timing_section](https://osu.ppy.sh/wiki/en/Beatmapping/Timing_section) | [Timing songs with #/8-signatures](https://osu.ppy.sh/wiki/en/Ranking_Criteria/Timing_Songs_With_8-Signatures) https://github.com/ppy/osu-wiki/pull/8126
- [x] Beats per minute #3232
- [x] Offset https://osu.ppy.sh/wiki/en/Beatmapping/Offset
- [x] Uninherited Timing Point https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timing#uninherited-timing-point
- [x] Inherited Timing Point https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timing#inherited-timing-point
- [x] Time Signature
---
- [x] Health Drain #3174
- [x] Circle Size #3175
- [x] Overall Difficulty #3187
- [x] Approach Rate #3306
---
- [x] Star Rating #3191
---
- [x] Beatmap Spotlights

**Comment by Pennek** [comment]
I'll be doing difficulty settings for osu! standard at least. Health Drain, Circle Size, Overall Difficulty and Approach Rate

**Comment by mcendu** [comment]
Is [the technical documentation for the .osu format suitable](https://osu.ppy.sh/help/wiki/osu!_File_Formats%2FOsu_(file_format)) for Beatmap Folder/.osu?

**Comment by cl8n** [comment]
yeah I'll just check that one off since .osu seems to be in a good state already

**Comment by paper-toaster** [comment]
I have a draft pr opened for creating a stub for the term "tech map" in #3774.

**Comment by Gamingzone123** [comment]
a couple of updates at to the state of which stubs still need to be written:

beatmap download is covered in "How to search for and download beatmaps" which is strangely only available in Chinese  https://osu.ppy.sh/wiki/en/Guides/Searching_and_Downloading_Beatmaps

beatmap creation is covered in the "Beatmapping" article https://osu.ppy.sh/wiki/en/Beatmapping

all three snap articles are covered by "beat snap", "Grid snap" and "distance snap" respectively https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Beat_Snap, https://osu.ppy.sh/wiki/en/Grid_snapping, https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Distance_snap

the editor is covered by 4 different articles (should probably be consolidated), "beatmap editor", "beatmap editor menu", "beatmapping and editor" and "beatmap editor timelines" https://osu.ppy.sh/wiki/en/Client/Beatmap_editor, https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Menu, https://osu.ppy.sh/wiki/en/Help_centre/Beatmapping, https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timelines

downbeat has an stub than needs expansion https://osu.ppy.sh/wiki/en/Downbeat

pattern, jump, and stream all have stubs needing expansion https://osu.ppy.sh/wiki/en/Beatmap/Pattern, https://osu.ppy.sh/wiki/en/Beatmap/Pattern/Jump, https://osu.ppy.sh/wiki/en/Beatmap/Pattern/Stream

antiflow has a stub https://osu.ppy.sh/wiki/en/Beatmapping/Antiflow

walk has a stub https://osu.ppy.sh/wiki/en/Gameplay/Walk

anchor may be covered by "slider anchor", the list doesn't make the type of anchor clear

timing is covered by at least 3 articles; "timing tab", "timing section" and "timing songs with #/8 signatures" https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timing, https://osu.ppy.sh/wiki/en/Beatmapping/Timing_section, https://osu.ppy.sh/wiki/en/Ranking_Criteria/Timing_Songs_With_8-Signatures

offset has a stub https://osu.ppy.sh/wiki/en/Beatmapping/Offset

both types of timing point are covered in "Timing tab" https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Timing

**Comment by Gamingzone123** [comment]
Beatmap submission may be covered in `Help_centre/Beatmapping`

**Comment by Walavouchey** [comment]
it's covered by https://osu.ppy.sh/wiki/en/Beatmapping/Beatmap_submission

**Comment by TicClick** [comment]
most of the items left here are about osu!mania patterns. I've found an o!m player who's willing to tick a few boxes, so expect an update in the following weeks.

**Comment by Walavouchey** [comment]
for some resources, a list of mania patterns can be found at https://osu.ppy.sh/wiki/en/Guides/osu!mania_Mapping_Guide#pattern

and here's an image i've had bookmarked from somewhere.

![](https://i.imgur.com/gta7ScK.jpeg)
