### ISSUE TITLE
Add Article Stubs (Modding)

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-wiki#3163]
See the main issue https://github.com/ppy/osu-wiki/issues/3143
See the project: https://github.com/ppy/osu-wiki/projects/3

Here you find all article stubs that need to be created. Some articles might already exist. Some articles can be deemed unnecessary as singular article and be summed up into a bigger article. 

Many of these singular topics are included as subset in some articles already or information is scattered around multiple articles. These articles might need to be split up into multiple ones and information must be pulled together into one common article then (e.g. https://github.com/ppy/osu-wiki/tree/master/wiki/Glossary)

Each article should only contain information of one topic. 

You can claim articles beforehand. Just comment here.

- [x] Modding v1 #6260
- [x] Beatmap Discussion (aka Modding v2) #3126
- [x] Time Stamp #3348
---
- [x] Ranked
- [x] Qualified
- [x] ~~Disqualified~~ (covered in Beatmap ranking procedure)
- [x] Unranked
- [x] ~~Nominated~~ (covered in Beatmap ranking procedure)
- [x] ~~Nuked~~ (covered in Modding/Nuke)
- [x] Loved
- [x] Approved
---
- [x] Proto Bubble #3173
- [x] Bubble #6239
- [x] Bubble Pop #6239
- [x] Veto Mediation
- [x] Veto
- [ ] Nomination
---
- [x] Kudosu #3307
- [x] Hype #3399
---
- [x] Mapping Assistance Team #3173
- [x] MAT Leaders #3173
- [x] Beatmap Approval Team / Beatmap Appreciation Team #3173
- [x] BAT Leaders #3173
---
- [x] NAT meetings #3461

**Comment by venix12** [comment]
i can probably do most of these

**Comment by JBHyperion** [comment]
With some research I could probably look into the various "Teams" stubs, though they were a little before I really got involved in the scene.

Everything else should be doable for me also, though isn't this pretty much a deconstructed Glossary in its current format? 🤔 Guess this is up to interpretation with:

> Some articles can be deemed unnecessary as singular article and be summed up into a bigger article.

**Comment by Pennek** [comment]
> isn't this pretty much a deconstructed Glossary in its current format?

as i've understood it that's pretty much the point for now. after we've built the foundation of stubs we can begin to link them together and go into more detail. eg. the 'slider'-article could go way more indepth about what a slider is, anchors, notepad creation, external programs, etc.

it's like constructing the wiki rabbit hole

**Comment by hypercyte** [comment]
I can create stubs for beatmap statuses (ranked, qualified etc.) 

Although depending on how they turn out, might be worth collating them all in one "Beatmap status" article maybe?

**Comment by Pennek** [comment]
Go for it! You can always add a "Main Page: Beatmap statuses" if deemed necessary

**Comment by cl8n** [comment]
I can't imagine you'd be able to meaningfully write a whole page about graveyard, wip, pending. the others might work as whole articles though. Loved already has this for example https://osu.ppy.sh/help/wiki/Beatmaps/History_of_Loved

short descriptions are already here https://osu.ppy.sh/help/wiki/Beatmaps but it's probably in the wrong place.

**Comment by DoryanR** [comment]
I'll see about making :

- Bubble
- Bubble Pop

**Comment by Gamingzone123** [comment]
it would probably be best to get a BN to do the nomination article, as that would provide the most accurate information

**Comment by Gamingzone123** [comment]
nomination is covered indirectly by parts from "beatmap nominators" and  "beatmap ranking procedure" https://osu.ppy.sh/wiki/en/People/The_Team/Beatmap_Nominators, https://osu.ppy.sh/wiki/en/Beatmap_ranking_procedure

**Comment by Walavouchey** [comment]
agree, they're basically covered

closing as all tasks are completed

**Comment by TicClick** [comment]
uhh no, this still needs to be a separate article

**Comment by Walavouchey** [comment]
just as nomination or the nomination process? the latter is covered by ranking procedure

**Comment by TicClick** [comment]
the former, due to the same reasons we have "Difficulty", or "Category", or "Hype" (these all are terms that deserve their own pages)

**Comment by Walavouchey** [comment]
I suppose it would be in [`Modding`](https://github.com/ppy/osu-wiki/tree/master/wiki/Modding) as `Modding/Nomination`

**Comment by TicClick** [comment]
inclined to close this still -- see #8254 for discussion. will refurbish that PR and rework it into a `Beatmap ranking procedure` update instead some time later.
