### ISSUE TITLE
Unify the style of the Tournaments articles

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#350]
## Tournaments

Every official osu! tournament organised by osu!team should be ported to GitHub or added.
The articles should live up to the ASG and be Markdown clear.

### Style

Style of all Tournament articles should match with style of the newest ones.

![](https://puu.sh/zuCmV/a15aad6dff.png)

>If there are groups, add them between Participants and Mappool with header level 2

>Check the TWC2017 for text and table templates

### List
- [x] `osu! World Cup`
   - [x] `osu! World Cup #1` - missing Tournament Schedule
   - [x] `osu! World Cup #2` - missing Tournament Schedule
   - [x] `osu! World Cup #3` - missing Match Results (unaccessable)
   - [x] `osu! World Cup 2013`
   - [x] `osu! World Cup 2014`
   - [x] `osu! World Cup 2015`
   - [x] `osu! World Cup 2016`
   - [x] `osu! World Cup 2017`
- [x] `osu!taiko World Cup`
   - [x] `2011 Taiko World Cup`
   - [x] `2012 Taiko World Cup` - doesn't exist
   - [x] `Taiko World Cup #3`
   - [x] `osu! Taiko World Cup 2014`
   - [x] `osu!taiko World Cup 2015`
   - [x] `osu!taiko World Cup 2016`
   - [x] `osu!taiko World Cup 2017`
   - [x] `osu!taiko World Cup 2018`
- [x] `Catch the Beat World Cup`
   - [x] `Catch the Beat World Cup`
   - [x] `Catch the Beat World Cup 2013`
   - [x] `Catch the Beat World Cup 2014` 
   - [x] `Catch the Beat World Cup 2015`
   - [x] `osu!catch World Cup 2016`
   - [x] `osu!catch World Cup 2017`
   - [x] `osu!catch World Cup 2018`
- [x] `osu!mania World Cup`
   - [x] `osu!mania World Cup 2014`
   - [x] `osu!mania World Cup 2015`
   - [x] `osu!mania 7K World Cup 2016` 
   - [x] `osu!mania 4K World Cup 2016`
   - [x] `osu!mania 7K World Cup 2017`
   - [x] `osu!mania 4K World Cup 2017`
   - [x] `osu!mania 7K World Cup 2018`
   - [x] `osu!mania 4K World Cup 2018`

**Comment by WalterToro** [comment]
As a note, I will be (slowly) working on the missing pages and some revisions and fixes on the finished pages, if anything, please ask ;)

**Comment by Joehuu** [comment]
I'll do all of TWC.

**Comment by fajar13k** [comment]
I want to take all CWC, but i'm unsure with the ruleset (in the first installment and 2013)

**Comment by Joehuu** [comment]
Might do TWC in the weekends as I had this burden since last August... sorry!

**Comment by WalterToro** [comment]
We are finally done, minor issues are there but the core of the issue is done.
Thanks to all contributors on this one!
