### ISSUE TITLE
osu!wiki to-do list

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#36]
A top-level overview of what is left to be completed for the new osu!client. Still a WIP, which means there's stuff to add which hasn't been added, but also potentially out-of-date items which need to be updated.

### About

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Accuracy

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Article Style Guide

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### BBCode

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### BanchoBot

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > AiMod

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Beat Snap Divisor

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Compose

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Design

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Distance Snap

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Kiai Time

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Menu

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > SB Load

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Song Setup

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Timelines

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmap Editor > Timing

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmapping

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmaps

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Beatmaps > Packs

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2009

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2010

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2011

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2012

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2013

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2014

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2015

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Best Of  > 2016

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Chat Console

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Contests

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Easy

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Normal

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Hard

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Insane

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Expert

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu!taiko

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Futsuu

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Kantan

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Muzukashii

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Oni

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Difficulties > osu! > Ura Oni

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Do you really want to ask peppy

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### FAQ

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Forums

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu! > v1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!catch

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!catch > v1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!mania

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!mania > v1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!taiko

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > osu!taiko  > v1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > T-Aiko!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > T-Aiko! > v1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > T-Aiko! > Interface

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > opsu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > osu!droid

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > osu!droid > Options

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > osu!stream

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > osu!stream > Song List

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modes > External Ports > osu!wp

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modifiers

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Game Modifiers > Summary

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Glossary

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Adding Custom Hit Sounds

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Audio Editing

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Changing the Artist or Title

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Changing the Title Text

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Collab Information

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Compressing Files

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Custom Hit Sound Library

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Custom Sample Overrides

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Getting Songs From Video Games

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > How to Time Songs

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Music Theory

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Setting the Offset on the Correct Beat

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Starting a Beatmap Project

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > Videos From Youtube

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Beatmapping > osu!mania Mapping Guide

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Miscellaneous > How to Run osu! on Your Mac Without Using Boot Camp

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Modding > Getting Your Map Modded

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Modding > How To Get Your Map Ranked

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > Beginner's Tutorial

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > GL Support Issues

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > How to Play osu!mania

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > How to Use the Offset Wizard

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > Recording osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > Searching and Downloading Beatmaps

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > Tablet Purchase

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Playing > Tips and Tricks on Skill Improvement

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Skinning > Cropping with Complex Backgrounds

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Skinning > Cropping with Simple Backgrounds

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Guides > Skinning > Making Properly Centered Spinners

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Help Center

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > 1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > 2

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > 3

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > 4

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > 5

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > 6

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > Release b335

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### History of osu! > osu!wiki

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Hit Objects

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### How You Can Help!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Index

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Installation

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Interface

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Internet Relay Chat

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Legal

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Legal > Copyright

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Legal > TOS

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Live streaming osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques 

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Basics

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Formations

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Jumps

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Making Good Sliders

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Rhythm

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Sliders

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Spinners

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mapping Techniques > Unrankable

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mascots

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Mascots > Gallery

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Medals > Beatmap Packs 0916

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Modding

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Multi

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Official Songs

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Options

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Options > Keyboard Bindings

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Options > Offset Wizard

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > Beatmap_Nomination_Group

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > Community_Contributors

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > Global_Moderation_Team

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > Language_Moderators

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > Quality_Assurance_Team

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > Support_Team

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > The Team

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### People > osu! Alumni

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Performance Points

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Performance Points > ppv1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Play Styles

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria > Code of Conduct

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria > Skin Set List

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria > osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria > osu!catch

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria > osu!mania

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Ranking Criteria > osu!taiko

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Registration

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Replay

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Reporting Bad Behaviour

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Reporting Bad Behaviour > Handling Cheating

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Rules

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Score 

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Score > Scorev1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Shortcut Key Reference

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Interface

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Sounds

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > osu!catch

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > osu!mania

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > osu!taiko

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > skin.ini

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > Interface

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > Sounds

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > osu!

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > osu!catch

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > osu!mania

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > osu!taiko

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Skinning > Tutorial > template

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Audio

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Cheat Sheet

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Commands

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Compound Commands

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > General Rules

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Miscellaneous

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Objects

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Shorthand

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > Variables

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboard Scripting > osu! File Toggles

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboarding

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboards

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Storyboards > Maps

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Submission > Beatmap Ranking Procedure

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tools > AiBat

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tools > SGL_Tool

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tools > osu!MapDownloader

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournament Drawings

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments Management Commands

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > CMT_4K > 2017

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > CWC > 2014

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > CWC > 2015

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > CWC > 2016

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > CWC > 2017

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > Countries that participated in osu! tournaments

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > MWC > 2014

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > MWC > 2015

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > MWC > 2016 > 4K

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > MWC > 2016 > 7K

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > MWC > 2017 > 4K

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > OWC > 1

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > OWC > 2

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > OWC > 2013

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > OWC > 2014

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > OWC > 2015

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > OWC > 2016

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > RMoT Invitational > 2

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > TWC > 2011

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > TWC > 2014

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > TWC > 2015

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > TWC > 2016

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > TWC > 2017

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Tournaments > osu! Tag Team Multiplayer Tournament

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Twitter

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### Welcome

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats > Db

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats > Osb

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats > Osk

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats > Osr

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats > Osu

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! File Formats > Osz

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! Program Files

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu! Program Files > User Configuration File

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu!academy

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu!supporter

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu!talk

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu!tourney

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

### osu!wiki Contribution Guide

- [ ] MD Clear
- [ ] ASG
- [ ] Up-to-date

**Comment by TPGPL** [comment]
Updated list

**Comment by iamanai** [comment]
It seems that a lot of the pages are very broken right now. Are we just migrating everything over first, then fixing things later? I'm fairly proficient in both MediaWiki and Markdown, so I'd be happy to help with article maintenance.

**Comment by Repflez** [comment]
@iamanai More or less that. Getting pages to look decently is a priority, though. Most of our efforts are coordinated on #osu-wiki at the [discord server](https://discord.gg/ppy).

**Comment by iamanai** [comment]
@repflez Alright, thanks. I'll look to the discord server for future queries.

**Comment by TPGPL** [comment]
List greatly changed

**Comment by TPGPL** [comment]
Updated list

**Comment by TPGPL** [comment]
Updated list

**Comment by MegaApplePi** [comment]
remove `How to do 15° Patterns` (I deleted it (in the form of technicalities, it was merged as a subsection in one of the articles))
also, I think you can now check all of the mapping techniques checkboxes since they were completed with the merge of #210

**Comment by MegaApplePi** [comment]
and the checkboxes from `Making Good Sliders`.. I just spotted an kink for a link to a technique but I'll look into it soon while I go through a bunch of articles

**Comment by TPGPL** [comment]
If you find anything missing/not checked, write here

**Comment by oralekin** [comment]
OWC 2016 #240

**Comment by TPGPL** [comment]
list greatly changed

**Comment by TPGPL** [comment]
Overhaul update

**Comment by TPGPL** [comment]
closing until i get an idea how to make this list good
