### ISSUE TITLE
List of articles in-need of cleanup

### ISSUE THREAD

**Issue by paper-toaster** [ppy/osu-wiki#3872]
Issue made to keep progress of wiki cleanup. 

You can claim articles that you want to cleanup here, just leave a comment; if you find an article that needs cleanup, but does not have the tag, also leave a comment and I'll add it to the list.

### Articles with `needs_cleanup` tag

- [x] BanchoBot —— #3962
- [ ] BBCode (@paper-toaster)
- [ ] Beatmaps\Packs
- [ ] Beatmaps\Distance_Snap
- [ ] FAQ (@paper-toaster) (backlog)
- [x] Game_modes —— #3965 
- [x] Game_modifier\Summary —— #3809
- [ ] Guides
  - [ ] How_to_Time_Songs
  - [x] Videos_from_Youtube —— #3851
- [ ] Help_Centre (@paper-toaster) (backlog)
- [ ] osu!academy
- [ ] Internet_Relay_Chat (@paper-toaster)
- [ ] Mascots\Gallery
- [ ] Medals\Beatmap_Packs_0916
- [ ] Multi (@paper-toaster)
- [ ] Options\Offset_Wizard
- [ ] osu!_Program_Files
- [x] Performance_Points —— #3781
- [ ] Replay
- [ ] Reporting_Bad_Behaviour
- [ ] Score (@paper-toaster) (backlog)
  - [ ] ScoreV1
- [ ] Skinning\History

### Articles that *should* have `needs_cleanup` tag, but don't
- [ ] Game_modes
  - [ ] osu!
  - [ ] osu!taiko
  - [ ] osu!catch
  - [ ] osu!mania
- [ ] osu!tourney\Troubleshooting
- [x] How_you_can_help!
- [x] History_of_osu!_2007 —— #3732
- [x] History_of_osu!_2008 —— #3737 
- [ ] OWC Articles —— #4365 (in review)

---

And because i have nowhere else to store this, here's a list of all the stubs that have been created and need expanding: 
[stubs.txt](https://github.com/ppy/osu-wiki/files/5093755/stubs.txt) (outdated)

**Comment by RockRoller01** [comment]
Don't see what is wrong with Skinning/History, pretty sure it has everything. Only things that may be missing are volume-bg and coin, tho I do not know if they ever were skinnable in the first place or if people just like to randomly add them to their mixed skins because someone added them as a joke at some point.

**Comment by paper-toaster** [comment]
> Don't see what is wrong with Skinning/History, pretty sure it has everything. Only things that may be missing are volume-bg and coin, tho I do not know if they ever were skinnable in the first place or if people just like to randomly add them to their mixed skins because someone added them as a joke at some point.

I didn't read through all the articles with the cleanup tag, so I can't say. If it's not missing anything, it's information is probably just badly worded/needs a spell and grammar check

**Comment by RockRoller01** [comment]
Ah ok. So I checked and volume-bg used to be skinnable apparently and the coin, tho the coin only for a single day as part of the april fools joke.
On selection-selectoptions it says "This element was removed for an unknown reason.". The reason for this is not verified, but pretty clear. The Beatmapinfoicon which can be found right of the leaderboard select dropdown replaced its functionality.

**Comment by paper-toaster** [comment]
> Ah ok. So I checked and volume-bg used to be skinnable apparently and the coin, tho the coin only for a single day as part of the april fools joke.
> On selection-selectoptions it says "This element was removed for an unknown reason.". The reason for this is not verified, but pretty clear. The Beatmapinfoicon which can be found right of the leaderboard select dropdown replaced its functionality.

If you have time, I'd greatly appreciate it if you added these elements to the article; the elements for these images are prob somewhere in the wiki/shared folder.

Also, I just skimmed thru the article, and it seems that the tag is there bc the article doesn't use an encyclopedic tone: inappropriate uses of article "you," inappropiately beginning sentences with "this," inconsistent capitalization, incorrect syntax, etc.

**Comment by RockRoller01** [comment]
Could probably add them and the Xk.ini files, but won't fix the wording. Should have the files in extract of the osu!ui.dll file

**Comment by cl8n** [comment]
these are on https://clayton.cc/osu-wiki-status/en now too, if you didn't see earlier. not sure if it's important to have this issue open anymore

> Articles that _should_ have `needs_cleanup` tag, but don't

why not add then 🤔

**Comment by paper-toaster** [comment]
Didn't know they were being labeled here. I've honestly just been using this as a to-do list to keep track of which articles have been clean and such. Will consider taking down

**Comment by cl8n** [comment]
it also shows stubs on the english page now, saw u pasted a list of those here
