### ISSUE TITLE
Refactor "Beatmaps", "Beatmapsets", and "Difficulties"

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#4723]
(based on peppy's feedback in #4711)
- [x] move `Beatmaps` to `Beatmap` and fix links
  - [x] `Beatmaps` -> `Beatmap` (#4724)
  - [x] `Beatmaps#category-name` -> `Beatmap/Category#category-name` (already done)
- [x] edit `Beatmap`, so that it's about beatmaps (formerly *beatmapsets*), and `Difficulties` is about difficulties
  - [x] rewrite the articles (#4773)
    - intro + difficulty
    - note about beatmaps being called *beatmapsets* in the past
    - another note on where to see a beatmap's/difficulty's identifier 
  - [x] delete `Beatmap_ID` and `Beatmapset_ID` and fix links and redirects (#4802)
  - [x] move stuff around (#4803)
    - move everything from `Beatmapsets` up a level into `Beatmap` and fix links
    - remove `Beatmapsets`
    - fix links: `Beatmapsets` -> `Beatmap`
    - fix redirects
- [x] move `Difficulties` to `Beatmap/Difficulty` and fix links and redirects (#4808)
- [ ] fix wording across the wiki (`beatmap` -> `difficulty` where applicable, `beatmapset` -> `beatmap`) (#5495 + #5530)

_Originally posted by @TicClick in https://github.com/ppy/osu-wiki/issues/4711#issuecomment-753738890_

**Comment by DoryanR** [comment]
Where are you on the last remaining point? If you are not on it I can see what I can do.

**Comment by TicClick** [comment]
I have it planned
