### ISSUE TITLE
Add several new categories and shut down `Glossary`

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#6080]
we have quite a few top-level categories already (such as `Beatmap`, `Beatmapping`, `Gameplay`, `Modding`, etc.)  which contain *most* of the relevant articles. I have a few ideas on where to go further:

- [x] the new top-level `Client` category: https://github.com/ppy/osu-wiki/pull/6627
  <details>
  <summary>what would be inside</summary>

  - [`Beatmap_Editor`](https://github.com/ppy/osu-wiki/tree/master/wiki/Beatmap_Editor) (12 articles)
  - [`Chat_Console`](https://github.com/ppy/osu-wiki/tree/master/wiki/Chat_Console)
  - [`Interface`](https://github.com/ppy/osu-wiki/tree/master/wiki/Interface)
  - [`Options`](https://github.com/ppy/osu-wiki/tree/master/wiki/Options)
  - [`osu!_Program_Files`](https://github.com/ppy/osu-wiki/tree/master/wiki/osu!_Program_Files) (1 article)
  - `osu! file formats` (5 articles or something)
  - see Walavouchey's comments down below
  </details>

- [x] ~~mode-specific categories for `Hit object`s (right now they are dumped together: [`Hit_object`](https://github.com/ppy/osu-wiki/tree/master/wiki/Hit_object))~~ after second, third, and fourth thoughts this doesn't look like it's really needed
- [x] disassemble `Glossary`. it's a blanket category anyway, and all of the articles in [`Glossary`](https://github.com/ppy/osu-wiki/tree/master/wiki/Glossary) may have their new homes already
- [x] the new `Music theory` category. this will include musical terms from the top level, such as `Beat`/`Downbeat`, and stuff from the current `Music theory` article (which should be split into several small articles as well), AND the timing-related articles/guides? need to hone this more
- [x] ~~a new `Series` category: articles such as `osu!academy`, `osu!talk`, `osu!mapping` will live here~~ a better idea: #6438
  - [x] check if the main page's community section should be updated accordingly https://github.com/ppy/osu-wiki/pull/8101
- [x] ~~(uncertain) move everything out of `The Team` category to `People`~~ no as per the last point of https://github.com/ppy/osu-wiki/issues/1698#issuecomment-917912450, or at least "not in foreseeable future"

### thoughts?

some of these ideas may make sense, some may not. specifically, I am not sure about including [`Game_modifier`](https://github.com/ppy/osu-wiki/tree/master/wiki/Game_modifier) (27 articles) and [`Hit_object`](https://github.com/ppy/osu-wiki/tree/master/wiki/Hit_object) (14 articles) into the Client category.

also, it will require setting up lots of new redirects. sucks, but better that than an unorganized mess, no?

### `Glossary`

<details><summary></summary>

- [x] [`Active_object`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Active_object/en.md) --> `Beatmapping/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Changelog`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Changelog/en.md) --> top-level https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Choke`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Choke/en.md) --> `Gameplay/`
- [x] [`Combobreak`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Combobreak/en.md) --> `Gameplay/Judgement/`
- [x] [`Comboburst`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Comboburst/en.md) --> `Gameplay/`
- [x] [`Combo_colour`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Combo_colour/en.md) --> `Beatmapping/`
- [x] [`Combo_fire`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Combo_fire/en.md) --> `Gameplay/`
- [x] [`Combo_milestone`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Combo_milestone/en.md) --> `Gameplay/`
- [x] [`Combo_multiplier_effect`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Combo_multiplier_effect/en.md) --> `Gameplay/`
- [x] [`Cookie`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Cookie/en.md) --> `Client/Interface`
- [x] [`Dash`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Dash/en.md) --> `Gameplay/`
- [x] [`Edge_dash`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Edge_dash/en.md) --> `Gameplay/`
- [x] [`Health_bar`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Health_bar/en.md) --> `Client/Interface/`
- [x] [`Hyperdash`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Hyperdash/en.md) --> `Gameplay/`
- [x] [`Ignore_list`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Ignore_list/en.md) --> `Client`
- [x] [`Lead-in`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Lead-in/en.md) --> `Beatmapping/` (it also defines it specifically as 3 seconds for some reason) https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Local_song_offset`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Local_song_offset/en.md) see https://github.com/ppy/osu-wiki/issues/7254
- [x] [`Loved`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Loved/en.md) - delete (duplicate of `Beatmap/Category#loved`)
- [x] [`Snapping`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Snapping/en.md) - split into a `Disambiguation` article pointing to `Gameplay/Snapping` and `Beatmapping/Snapping`
- [x] [`Touhosu!`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Touhosu!/en.md) - delete and merge with `History_of_osu!/April_Fools` https://github.com/ppy/osu-wiki/pull/8103
- [x] [`Trigger_distance`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Trigger_distance/en.md) --> `Beatmapping/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Walk`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Walk/en.md) --> `Gameplay/`

</details>

### `Beatmap`

<details><summary></summary>

- [x] [`Authentic`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Authentic/en.md)
- [x] [`Background`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Background/en.md)
- [x] [`Beatmap_collaborations`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Beatmap_collaborations/en.md)
- [x] [`Beatmap_description`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Beatmap_description/en.md)
- [x] [`Beatmap_host`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Beatmap_host/en.md)
- [x] [`Break`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Break/en.md)
- [x] [`Category`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Category/en.md)
- [x] [`Difficulty`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Difficulty/en.md)
- [x] [`Genre_and_language`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Genre_and_language/en.md)
- [x] [`Guest_difficulty`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Guest_difficulty/en.md)
- [x] [`History_of_Loved`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/History_of_Loved/en.md) --> `History_of_osu!/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Hype`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Hype/en.md)
- [x] [`Marathon`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Marathon/en.md)
- [x] [`Online_offset`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Online_offset/en.md) see https://github.com/ppy/osu-wiki/issues/7254
- [x] [`Packs`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Packs/en.md)
- [x] [`Pattern`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Pattern/en.md)
- [x] [`Primary_metadata_source`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Primary_metadata_source/en.md)
- [x] [`TAG`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/TAG/en.md)
- [x] [`Technical_maps`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Technical_maps/en.md)
- [x] [`Title_Text`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Title_Text/en.md)
</details>

### `Beatmapping`

<details><summary></summary>

- [x] [`Antiflow`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Antiflow/en.md) --> `Beatmapping/Mapping_techniques/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Approach_rate`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Approach_rate/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Beats_per_minute`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Beats_per_minute/en.md)
- [x] [`Circle_size`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Circle_size/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Colourhaxing`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Colourhaxing/en.md)
- [x] [`Combo`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Combo/en.md)
- [x] [`Countdown`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Countdown/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Health`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Health/en.md) --> `Gameplay/`
- [x] [`Health_drain`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Health_drain/en.md) - merge with `Health`
- [x] [`Hitsound`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Hitsound/en.md)
- [x] [`HP_drain_rate`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/HP_drain_rate/en.md) -- `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`New_combo`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/New_combo/en.md)
- [x] [`Offset`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Offset/en.md) see https://github.com/ppy/osu-wiki/issues/7254
- [x] [`Overall_difficulty`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Overall_difficulty/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Overmapping`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Overmapping/en.md)
- [x] [`Sampleset`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Sampleset/en.md)
- [x] [`Slider_tick`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Slider_tick/en.md) --> `Gameplay/Hit_object/Slider/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Slider_tick_rate`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Slider_tick_rate/en.md)
- [x] [`Snapping`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Snapping/en.md)
- [x] [`Song_compilation`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Song_compilation/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Star_rating`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Star_rating/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Time_signature`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Time_signature/en.md)
- [x] [`Timing_section`](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Timing_section/en.md)

</details>

### `Gameplay`

<details><summary></summary>

- [x] [`Accuracy`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Accuracy/en.md)
- [x] [`Combo_(score_multiplier)`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Combo_(score_multiplier)/en.md)
- [x] [`Drain_time`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Drain_time/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Fingerlock`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Fingerlock/en.md)
- [x] [`Grade`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Grade/en.md)
- [x] [`Input_device`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Input_device/en.md)
- [x] [`Judgement`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Judgement/en.md)
- [x] [`Mind_block`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Mind_block/en.md)
- [x] [`Notelock`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Notelock/en.md) --> `Gameplay/Judgement/`
- [x] [`Play_time`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Play_time/en.md) --> `Beatmap/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Slider_break`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Slider_break/en.md) --> `Gameplay/Judgement/`
- [x] [`Spectating`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Spectating/en.md)
- [x] [`Tablet_cover`](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Tablet_cover/en.md)

</details>

### Top-level

<details><summary></summary>

- [x] [`Contributor_Code_of_Conduct`](https://github.com/ppy/osu-wiki/blob/master/wiki/Contributor_Code_of_Conduct/en.md) --> `Rules/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Geki`](https://github.com/ppy/osu-wiki/blob/master/wiki/Geki/en.md) --> `Gameplay/Judgement/`
- [x] [`Katu`](https://github.com/ppy/osu-wiki/blob/master/wiki/Katu/en.md) --> `Gameplay/Judgement/`
- [x] [`Grade`](https://github.com/ppy/osu-wiki/blob/master/wiki/Grade/en.md) - delete and merge with `Gameplay/Grade`
- [x] [`Grid_snapping`](https://github.com/ppy/osu-wiki/blob/master/wiki/Grid_snapping/en.md) --> `Beatmapping` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Hit_object`](https://github.com/ppy/osu-wiki/blob/master/wiki/Hit_object/en.md) --> `Gameplay/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Installation`](https://github.com/ppy/osu-wiki/blob/master/wiki/Installation/en.md) --> `Client/`
- [x] [`Interface`](https://github.com/ppy/osu-wiki/blob/master/wiki/Interface/en.md) --> `Client/`
- [x] [`Kiai_time`](https://github.com/ppy/osu-wiki/blob/master/wiki/Kiai_time/en.md) --> `Gameplay/`
- [x] [`Mapping_Techniques`](https://github.com/ppy/osu-wiki/blob/master/wiki/Mapping_Techniques/en.md) --> `Beatmapping/Mapping_techniques` (rename to sentence case) https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Mapping_and_Modding_Timeline`](https://github.com/ppy/osu-wiki/blob/master/wiki/Mapping_and_Modding_Timeline/en.md) --> `History_of_osu!/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Multi`](https://github.com/ppy/osu-wiki/blob/master/wiki/Multi/en.md) --> `Gameplay/` (with interface descriptions eventually split into an article in `Client/Interface/`)
- [x] [`Game_modifier`](https://github.com/ppy/osu-wiki/blob/master/wiki/Game_modifier/en.md) --> `Gameplay/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Options`](https://github.com/ppy/osu-wiki/blob/master/wiki/Options/en.md) --> `Client/`
- [x] [`Recalculate_slider_lengths`](https://github.com/ppy/osu-wiki/blob/master/wiki/Recalculate_slider_lengths/en.md) --> `Beatmap_Editor/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Shortcut_key_reference`](https://github.com/ppy/osu-wiki/blob/master/wiki/Shortcut_key_reference/en.md) --> `Client/`
- [x] [`Pass`](https://github.com/ppy/osu-wiki/blob/master/wiki/Pass/en.md) --> `Gameplay/`
- [x] [`Play_style`](https://github.com/ppy/osu-wiki/blob/master/wiki/Play_style/en.md) --> `Gameplay/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Replay`](https://github.com/ppy/osu-wiki/blob/master/wiki/Replay/en.md) --> `Gameplay/`
- [x] [`Resnap`](https://github.com/ppy/osu-wiki/blob/master/wiki/Resnap/en.md) --> `Beatmap_Editor/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Submission`](https://github.com/ppy/osu-wiki/blob/master/wiki/Submission/en.md) --> `Beatmapping/Beatmap_submission` (rename) https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Chat_Console`](https://github.com/ppy/osu-wiki/blob/master/wiki/Chat_Console/en.md) --> `Client/Interface/`
- [x] [`Staff_log`](https://github.com/ppy/osu-wiki/blob/master/wiki/Staff_log/en.md) --> `People/The_Team/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`User_title`](https://github.com/ppy/osu-wiki/blob/master/wiki/User_title/en.md) --> `Community/` https://github.com/ppy/osu-wiki/pull/7187
- [x] [`Universal_offset`](https://github.com/ppy/osu-wiki/blob/master/wiki/Universal_offset/en.md) see https://github.com/ppy/osu-wiki/issues/7254
- [x] [`Visual_settings`](https://github.com/ppy/osu-wiki/blob/master/wiki/Visual_settings/en.md) --> `Client/Interface/`
- [x] [`osu!_File_Formats`](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_File_Formats/en.md) --> `Client/osu!_file_formats` (rename to sentence case)
- [x] [`osu!_Program_Files`](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_Program_Files/en.md) --> `Client/osu!_program_files` (rename to sentence case)
- [x] [`osu!coin`](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!coin/en.md) --> `History_of_osu!/April_Fools/` (or merge into the `April_Fools` article) https://github.com/ppy/osu-wiki/pull/7187
- [x] [`osu!pixel`](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!pixel/en.md) --> `Beatmap_Editor/osu!_pixel` (rename) (would link to and get linked to in [`Storyboarding/Specifications/Concepts/Coordinate_space`](https://github.com/ppy/osu-wiki/issues/4827#issuecomment-990741545)) https://github.com/ppy/osu-wiki/pull/7187

</details>

## General notes

- The offset articles are to be put under a top-level `Offset` article
- HP, CS, HP and OD articles --> `Beatmap/`

**Comment by Walavouchey** [comment]
some opinions:

- [`Submission`](https://github.com/ppy/osu-wiki/tree/master/wiki/Submission) should be in `Beatmapping` and be renamed `Beatmap_submission` (not to be confused with score submission)
- [`Kiai_time`](https://github.com/ppy/osu-wiki/blob/master/wiki/Kiai_time/en.md), [`Replay`](https://github.com/ppy/osu-wiki/tree/master/wiki/Replay), [`Hit_object`](https://github.com/ppy/osu-wiki/tree/master/wiki/Hit_object), [`Game_modifier`](https://github.com/ppy/osu-wiki/tree/master/wiki/Game_modifier), and those combo articles you mention should all be in `Gameplay`
- `Series` should instead be `Community`
- `Timing` should just be a `Music_theory` folder with all of the split articles you've mentioned

hopefully most of these are obvious - i've tried to look at it in terms of "categorical correctness". anything in a `Client` category should really only be about the game client interface and how to navigate it (as well as the program file listings. something like `Installation` would also fit there).

`Replay` in `Gameplay` might contradict this on the surface, but it semantically fits and there's `Spectating` in there as well. The interface descriptions in `Replay` should really be in `Interface` anyway (which also should be split into a folder), but i digress

**Comment by TicClick** [comment]
agree to everything you say here, except for one moment: if `Series` is `Community`, then it will be odd to have all these talks in the same category as community-related articles, such as silence/chat/forum/user titles/anything else similar?

**Comment by Bazzadwarf** [comment]
I don't really like how the tournament folder structure is currently handled, while the main page is good for finding tournaments that have wiki pages, it's not friendly for expanding the section to include other useful info.

Some sort of structure like this could work:
- `Tournaments`
  - `Community Tournaments`
    - `3TWC`
    - `3WC`
    - `4DM`
    - etc...
  - `Countries that participated in osu! tournaments`
  - `Official Support`
  - `Official World Cups`
    - `OWC`
    - `TWC`
    - `CWC`
    - `MWC`
  - `Tournament Drawings`

**Comment by Gamingzone123** [comment]
Downbeat shoul probably go under Music_theory which should probably be under Beatmapping

**Comment by Walavouchey** [comment]
On the note of `Series` and [adding a `Community`](https://discord.com/channels/188630481301012481/218677502141399041/913400728683438131) category, how about putting these community video series as `Community/Video_series`

I can also sort of see them put in `Guides` as a "Video guides" section (except for osu!talk) which could also include other video guides on youtube

> Downbeat should probably go under Music_theory which should probably be under Beatmapping

Yes for the first part but no for the latter, because music theory isn't solely related to mapping (think skinning, hitsounding, storyboarding etc.

**Comment by TicClick** [comment]
good thought. I'll take it!

**Comment by Walavouchey** [comment]
compiling various discussion on discord and this issue, (and a bit more of me going through everything)

# `Glossary`

- `Active_object` --> `Beatmapping/`
- `Changelog` --> top-level
- `Choke` --> `Gameplay/`
- `Combobreak` --> `Gameplay`
- `Comboburst` --> `Gameplay/`
- `Combo_colour` --> either `Gameplay/Hit_object`, `Beatmap` (or just `Beatmapping` and alternatively merge with `Beatmapping/Combo` because it's almost a duplicate), but very unsure
- `Combo_fire` --> `Gameplay/`
- `Combo_milestone` --> `Gameplay/`
- `Combo_multiplier_effect` --> `Gameplay/`
- `Cookie` --> `Client/Interface`
- `Dash` --> `Gameplay/`
- `Edge_dash` --> `Gameplay/`
- `Health_bar` --> `Client/Interface/`
- `Hyperdash` --> `Gameplay/`
- `Ignore_list` --> `Client`
- `Lead-in` --> `Beatmapping/` (it also defines it specifically as 3 seconds for some reason)
- `Local_song_offset` --> `Gameplay/`
- `Loved` - delete (duplicate of `Beatmap/Category#loved`)
- `Snapping` --> `Beatmapping/`
- `Touhosu!` --> `History_of_osu!/April_Fools/` (or merge into the `April_Fools` article)
- `Trigger_distance` --> `Beatmapping/`
- `Walk` --> `Gameplay/`

# `Beatmap`

- `Authentic`
- `Background`
- `Beatmap_collaborations`
- `Beatmap_description`
- `Beatmap_host`
- `Break`
- `Category`
- `Difficulty`
- `Genre_and_language`
- `Guest_difficulty`
- `History_of_Loved`
- `Hype`
- `Marathon`
- `Online_offset`
- `Packs`
- `Pattern`
- `Primary_metadata_source`
- `TAG`
- `Technical_maps`
- `Title_Text`

# `Beatmapping`

- `Antiflow`
- `Approach_rate`
- `Beats_per_minute`
- `Circle_size`
- `Colourhaxing`
- `Combo`
- `Countdown` --> `Beatmap/`
- `Health` --> `Gameplay/`
- `Health_drain` - merge with `Health`
- `Hitsound`
- `HP_drain_rate`
- `New_combo`
- `Offset`
- `Overall_difficulty`
- `Overmapping`
- `Sampleset`
- `Slider_tick` --> `Gameplay/Hit_object/Slider/`
- `Slider_tick_rate`
- `Snapping`
- `Song_compilation` --> `Beatmap/`
- `Star_rating` --> `Beatmap/`
- `Time_signature`
- `Timing_section`

# `Gameplay`

- `Accuracy`
- `Combo_(score_multiplier)`
- `Drain_time`
- `Fingerlock`
- `Grade`
- `Input_device`
- `Judgement`
- `Mind_block`
- `Notelock`
- `Play_time`
- `Slider_break`
- `Spectating`
- `Tablet_cover`

# Top-level

- `Geki` --> `Gameplay/Score`
- `Katu` --> `Gameplay/Judgement`
- `Grade` - delete and merge with `Gameplay/Grade`
- `Grid_snapping` --> `Beatmapping`
- `Hit_object` --> `Gameplay`
- `Installation` --> `Client/`
- `Interface` --> `Client/`
- `Kiai_time` --> `Gameplay/`
- `Mapping_Techniques` --> `Beatmapping/Mapping_techniques` (rename to sentence case)
- `Mapping_and_Modding_Timeline` --> `History_of_osu!/`
- `Multi` --> `Gameplay/`
- `Options` --> `Client/Options`
- `Recalculate_slider_lengths` --> `Beatmap_Editor/`
- `Shortcut_key_reference` --> `Client/`
- `Pass` --> `Gameplay/`
- `Play_style` --> `Gameplay/`
- `Replay` --> `Gameplay/`
- `Resnap` --> `Beatmap_Editor/`
- `Submission` --> `Beatmapping/Beatmap_submission` (rename)
- `Chat_Console` --> `Client/Interface/`
- `Silence` --> `Community/`
- `Staff_log` --> `History_of_osu!`
- `User_title` --> `Community`
- `Universal_offset` --> `Gameplay` (just like `Local_song_offset`)
- `Visual_settings` --> `Client/Interface`
- `osu!_File_Formats` --> `Client/osu!_file_formats` (rename to sentence case)
- `osu!_Program_Files` --> `Client/osu!_program_files` (rename to sentence case)
- `osu!coin` --> `History_of_osu!/April_Fools/` (or merge into the `April_Fools` article)
- `osu!pixel` --> `Beatmap/osu!_pixel` (rename) (this would also get covered by [`Storyboarding/Specifications/Concepts/Coordinate_space`](https://github.com/ppy/osu-wiki/issues/4827#issuecomment-990741545))

this should probably make discussion easier, i'll edit this over time as we get to a consensus

> [there may be too much of `everything that needs to be there`](https://discord.com/channels/188630481301012481/218677502141399041/923237134020792360)

you sure were right

**Comment by TicClick** [comment]
^ comments:

### `Glossary`

- `Combo colour` - that's `Beatmapping`
- `Local song offset` - I'd still put that under `Beatmapping/Timing` with other offsets
- `Snapping`: may also refer to a) near-immediate cursor positioning over hit objects or b) BSD (objects being attached to specific timeline ticks), so worth a `Disambiguation` article

### `Beatmap`

- `History of Loved` - maybe it should be in `History of osu!`

### `Gameplay`

- `Drain time` and `Play time` are components of a `Beatmap`

### `Top level`

- `Contributor code of conduct` should go to `Rules`
- `Geki` is also a form of `Gameplay/Judgement`
- `osu!pixel` mostly makes sense in context of `Beatmap Editor`
- `Silence` - while logically it's a part of `Community`, it has no place in current structure. I considered making a category that'd revolve around rules and all that stuff, but ended up doing nothing due to lack of specific ideas

**Comment by Walavouchey** [comment]
> `Geki` is also a form of `Gameplay/Judgement`

oh right that's me being dumb

> `Silence` ... I considered making a category that'd revolve around rules and all that stuff

why not in `Rules`?

> `Local song offset` - I'd still put that under `Beatmapping/Timing` with other offsets

you mean create `Beatmapping/Timing/` and put `Glossary/Local_song_offset`, `Universal_offset` and `Beatmap/Online_offset` there?

maybe also delete `Beatmapping/Timing_section` in favour of `Beatmap_Editor/Timing`?

> `Snapping` may also refer to a) near-immediate cursor positioning over hit objects or b) BSD (objects being attached to specific timeline ticks), so worth a `Disambiguation` article

- [`Snapping`](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Snapping/en.md) - split into a `Disambiguation` article pointing to `Gameplay/Snapping` and `Beatmapping/Snapping`?

**Comment by Walavouchey** [comment]
[more discussion on discord](https://discord.com/channels/188630481301012481/218677502141399041/923284562547728444)

**Comment by Walavouchey** [comment]
I've moved the big task list from [my comment](https://github.com/ppy/osu-wiki/issues/6080#issuecomment-999743448) to op to integrate it with the issue task counter

**Comment by Walavouchey** [comment]
Putting down some discussion points/reasoning for a few items mainly in response to the above pr

- `Universal_offset` fits in `Client/Options`, but should `Local_song_offset` also go there, instead of `Beatmapping/Timing` or `Beatmap`? it's saved per beatmap, but it's not part of the beatmap (while `Online_offset` definitely is).
    - Advantage would be having these offset articles in two places instead of three
    - Tbh maybe we should have one top-level `Offset` article containing all of these and everything else about offsets
- `Active_object` is both a catch mapping term (objects that maintain combo) as well as an osu! mapping term (objects you click on), so they'd both go in `Beatmapping` along with a disambiguation page
- While `Combo_colour` and `Lead-in` could be in `Gameplay` or `Beatmap`, the articles themselves are written in the context of `Beatmapping`. If they were in `gameplay` for instance, stuff like colourhaxing or any other potential information wouldn't make sense to be mentioned in them (and `Colourhaxing` is already in `Beatmapping`)

**Comment by TicClick** [comment]
hesitant to merge health drain and health because these are related yet different things: https://github.com/ppy/osu-wiki/pull/3174

**Comment by Walavouchey** [comment]
health drain is just the term for health draining, while HP drain rate is the beatmap diff setting. health drain does not need its own article, and can be a tag in health as it's already explained there.

the reason it was split out in the first place seems to have been because health was originally written in terms of beatmapping and its health drain section was more about gameplay, but to me the health article (largely unchanged since) looks to be all about a gameplay mechanic so it seems like a weird decision.
