### ISSUE TITLE
Adopt new flag syntax

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#7138]
# syntax

https://github.com/ppy/osu-web/pull/8561

# scope of work

- [x] make sure an issue about supporting this client-side exists in https://github.com/ppy/osu, and link it here https://github.com/ppy/osu/issues/20591
- [x] add usage rules to the article styling criteria https://github.com/ppy/osu-wiki/pull/7681
  - [x] maybe clarify that quotes aren't necessary
- [x] ~~find a way to showcase the flags similarly to what we have in https://github.com/ppy/osu-wiki/tree/master/meta/flag-references~~ not necessary
- [x] replace the reference-style flag images everywhere in the wiki with the new syntax tags https://github.com/ppy/osu-wiki/pull/7681

# extra

- [ ] make one of our linters recognize and check the new tag https://github.com/ppy/osu-wiki/issues/8135
- [x] deprecate or rework @MegaApplePi's [flag link generator](https://github.com/ppy/osu-wiki/issues/328)
- [x] deprecate @cl8n's flag checker https://github.com/cl8n/osu-wiki-bin/blob/master/src/commands/update-flags.ts

**Comment by TicClick** [comment]
@Walavouchey tentatively assigning you since we had a conversation about this

**Comment by cl8n** [comment]
what did you have in mind for lint checks on these? I can't think of anything useful

**Comment by TicClick** [comment]
nothing specific. maybe something simple to make sure it's exactly of the `::{ flag="" }::` format, with two colons surrounding curly braces that have a `flag="XX"` piece — I take that a typo in either part won't be caught by remark

**Comment by RockRoller01** [comment]
> maybe something simple to make sure it's exactly of the `::{ flag="" }::` format
Actually I have been informed that despite the PR on osu-web showing the quotes, they are actually not required. Noticed that TPGPLs version of mass flag replacement unlike mine had ~15k difference in numbers, which is when I was made aware of this by clayton.

**Comment by Walavouchey** [comment]
closing as the remaining task has its own issue now
