### ISSUE TITLE
Clean up, update, and complete the `Gameplay` articles

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#9919]
## New articles

- [ ] `Fail` (since we have `Pass`)

## Clean up

- [ ] `Accuracy`: see TODOs in the article
- [ ] `Combo (score multiplier)`: better structure, a screenshot or two, perhaps add extra information and links to related articles
- [ ] `Fingerlock`: stub + could be rewritten for ease of reading
- [ ] `Health`: better structure, see what could be moved to/from `Beatmap/HP drain rate` and `Client/Interface/Health bar`
- [ ] `Replay`: needs a rewrite + update
- [ ] `Tablet cover`: stub + may benefit from a rewrite + see TODOs in the article

## Large issues

- [ ] Clean up and complete the `Game modifier` articles
- [ ] Clean up and complete the `Hit object` articles
- [ ] Clean up and complete the `Input device` articles
- [ ] Clean up and complete the `Judgement` articles
- [ ] Clean up and complete the `Play style` articles
- [ ] Clean up and complete the `Score` articles https://github.com/ppy/osu-wiki/issues/6431

## Complete

- [ ] index article (`/wiki/Gameplay`): it's empty -- should have at least a paragraph or two, and contain at least article categories instead of a very long plain list
- [x] `Choke`: good enough
- [ ] `Combo milestone`: stub
- [ ] `Combo multiplier effect`: stub
- [ ] `Combo burst`: stub
- [ ] `Dash`: stub
- [x] `Dash snapping`: good enough
- [ ] `Edge dash`: stub + missing images
- [ ] `Full combo`: stub
- [ ] `Grade`: add grade images
- [ ] `Hyperdash`: stub
- [x] `Kiai time`: good enough
- [ ] `Mind block`: stub
- [ ] `Pass`: stub
- [ ] `Spectating`: stub + cross-reference with `Replay`
- [ ] `Spinner trap`: stub + missing images
- [ ] `Walk` : stub
