### ISSUE TITLE
Update/complete the `Game modifier` articles

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#9920]
- [ ] `10K`: stub + see TODOs in the article
- [ ] `Auto`
- [ ] `Autopilot`
- [ ] `Cinema`
- [ ] `Co-op`
- [x] `Double time`: good enough
- [ ] `Easy`
- [ ] `Fade In`
- [ ] `Fade Out`: stub + see TODOs in the article
- [ ] `Flashlight`: stub + perhaps needs a small rewrite and cleanup
- [ ] `Half Time`
- [ ] `Hard Rock`
- [ ] `Hidden`
- [ ] `Mirror`
- [ ] `Mod multiplier`
- [ ] `Nightcore`
- [ ] `No Fail`
- [ ] `No Video`: stub + see TODO in the article
- [ ] `Perfect`
- [ ] `Random`
- [ ] `Relax`
- [ ] `ScoreV2`
- [ ] `Spun Out`: stub + needs a title fix
- [ ] `Sudden Death`
- [ ] `Summary`: need to decide if we still want it -- overlaps with the index page (`/wiki/Gameplay/Game_modifier`) so probably can be merged into that
- [ ] `Target Practice`
- [ ] `xK`
